### ISSUE TITLE
No detailed coli tracking

### ISSUE THREAD

**Issue by 2hdlockness** [seeshaughnessy/MMM-OneTracker#2]
Hello
I can see my packages, but I am just getting the information in transit on the application. In addition, the delivered packages immediately disappear from the application.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/1rLKbWW/Sans-titre.png" alt="Sans-titre" border="0"></a>

**Comment by seeshaughnessy** [comment]
Can you tell me what happens when you check your status using the one tracker phone app? This module checks the "tracking_time_estimated" data from the API to determine how many days are estimated to delivery. If no data was sent to the one tracker API then it shows a 00 date/time, which I've translated to a generic "In transit" time. The same goes for delivery. The way I can tell if the delivery should show or be cleared is if the package is marked as 'delivered' and the "tracking_time_estimated" is set to the current day.

Most services have worked for me, but Amazon doesn't update the "tracking_time_estimated" data, so I always see it as "In Transit" instead of receiving an estimated time.

 If one tracker has information available that can improve this I can try to update the file, but when I worked with this it was a limitation of the API (and if the carrier sends one tracker the information).
